<?
$aMenuLinks = Array(
    Array(
        "Банкетный зал",
        "/meropriyatiya/banket/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Конференц-зал",
        "/meropriyatiya/konferenc/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новый год",
        "/meropriyatiya/newyear/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Корпоратив",
        "/meropriyatiya/korporativ/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Тимбилдинг",
        "/meropriyatiya/teambuild/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Свадьба",
        "/meropriyatiya/svadba/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Юбилей",
        "/meropriyatiya/yubilei/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Детский праздник",
        "/meropriyatiya/kids/",
        Array(),
        Array(),
        ""
    ),

);
?>