<?
$aMenuLinks = Array(
    Array(
        "ГЛАВНАЯ",
        "../..",
        Array(),
        Array(),
        ""
    ),
    Array(
        "ПРОЖИВАНИЕ",
        "/prozhivanie/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "ВПЕЧАТЛЕНИЯ",
        "/vpechatleniya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "РЕСТОРАН",
        "/restoran/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "МЕРОПРИЯТИЯ",
        "/meropriyatiya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "ГАЛЕРЕЯ",
        "/galereya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "СПЕЦПРЕДЛОЖЕНИЯ",
        "/spetspredlozheniya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "КОНТАКТЫ",
        "/kontakty/",
        Array(),
        Array(),
        ""
    )
);
?>